---
resources:
- name: cf-buildpack-image-src
  type: git
  source:
    uri: https://github.com/18F/cf-dockerized-buildpack.git
    branch: pipeline

- name: cflinuxfs2-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release

- name: registry-image
  type: docker-image
  source:
    repository: registry

- name: python-buildpack-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/python-buildpack-release

- name: registry-auth-s3
  type: s3
  source:
    server_side_encryption: AES256
    region_name: {{s3_region}}
    bucket: {{s3_bucket}}
    versioned_file: jobstorage/registry-service-auth

jobs:
- name: deploy-docker-registry
  serial: true
  plan:
  - get: cf-buildpack-image-src
  - get: registry-image
    trigger: true
  - task: deploy-registry
    file: cf-buildpack-image-src/ci/deploy-registry.yml
    params:
      CF_API: {{cf_api}}
      CF_USER: {{cf_username}}
      CF_PASS: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
      APP_NAME: {{registry_app_name}}
  - put: registry-auth-s3
    params:
      file: build/registry-service-auth

- name: update-python-image
  serial: true
  plan:
  - get: cf-buildpack-image-src
    trigger: true
    passed: [deploy-docker-registry]
  - get: python-buildpack-release
    trigger: true
  - get: cflinuxfs2-release
    trigger: true
  - get: registry-auth-s3
  - task: do-build-args
    file: cf-buildpack-image-src/ci/do-build-args.yml
    params:
      LANGUAGE: python
